In [1]:
import yaml
from benchmark import run_benchmark_from_notebook

In [2]:


# Path to your configuration file
config_path = "CHILI_trivial.yaml"

# Run the benchmark
results = run_benchmark_from_notebook(config_path, use_cpu=False)

# Display the results
results

Using device: cuda
Validating dataset (max atoms: 100)...
Dataset validation successful - all structures have appropriate atom counts.
Dataset: CHILI-3K
Task: AbsPositionRegressionxPDF
Model: MLP
Training samples: 2031
Validation samples: 255
Test samples: 255

Running with seed: 42

Model Summary for MLP:
Total trainable parameters: 403,564 (404k)
Model architecture:
BaselineMLP(
  (model): Sequential(
    (0): Linear(in_features=6000, out_features=64, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.5, inplace=False)
    (3): Linear(in_features=64, out_features=300, bias=True)
  )
)
Epoch: 1/100, Train Loss: 2.0768, Val PositionMAE: 5.0534
Epoch: 2/100, Train Loss: 2.0758, Val PositionMAE: 5.0518
Epoch: 3/100, Train Loss: 2.0752, Val PositionMAE: 5.0505
Epoch: 4/100, Train Loss: 2.0752, Val PositionMAE: 5.0496
Epoch: 5/100, Train Loss: 2.0737, Val PositionMAE: 5.0489
Epoch: 6/100, Train Loss: 2.0720, Val PositionMAE: 5.0484
Epoch: 7/100, Train Loss: 2.0728, Val PositionMAE: 5.0480
Epoch: 8/100, Train Loss: 2.0728, Val PositionMAE: 5.0476
Epoch: 9/100, Train Loss: 2.0718, Val PositionMAE: 5.0473
Epoch: 10/100, Train Loss: 2.0721, Val PositionMAE: 5.0470
Epoch: 11/100, Train Loss: 2.0719, Val PositionMAE: 5.0468
Epoch: 12/100, Train Loss: 2.0713, Val PositionMAE: 5.0467
Epoch: 13/100, Train Loss: 2.0705, Val PositionMAE: 5.0466
Epoch: 14/100, Train Loss: 2.0698, Val PositionMAE: 5.0465
Epoch: 15/100, Train Loss: 2.0702, Val PositionMAE: 5.0465
Epoch: 16/100, Train Loss: 2.0703, Val PositionMAE: 5.0464
Epoch: 17/100, Train Loss: 2.0704, Val PositionMAE: 5.0464
Epoch: 18/100, Train Loss: 2.0697, Val PositionMAE: 5.0464
Epoch: 19/100, Train Loss: 2.0701, Val PositionMAE: 5.0464
Epoch: 20/100, Train Loss: 2.0697, Val PositionMAE: 5.0465
Epoch: 21/100, Train Loss: 2.0700, Val PositionMAE: 5.0465
Epoch: 22/100, Train Loss: 2.0690, Val PositionMAE: 5.0465
Epoch: 23/100, Train Loss: 2.0695, Val PositionMAE: 5.0466
Epoch: 24/100, Train Loss: 2.0692, Val PositionMAE: 5.0466
Epoch: 25/100, Train Loss: 2.0705, Val PositionMAE: 5.0467
Epoch: 26/100, Train Loss: 2.0686, Val PositionMAE: 5.0467
Epoch: 27/100, Train Loss: 2.0708, Val PositionMAE: 5.0468
Epoch: 28/100, Train Loss: 2.0689, Val PositionMAE: 5.0469
Maximum patience reached
Test PositionMAE: 5.0198

Running with seed: 43

Model Summary for MLP:
Total trainable parameters: 403,564 (404k)
Model architecture:
BaselineMLP(
  (model): Sequential(
    (0): Linear(in_features=6000, out_features=64, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.5, inplace=False)
    (3): Linear(in_features=64, out_features=300, bias=True)
  )
)
Epoch: 1/100, Train Loss: 2.0771, Val PositionMAE: 5.0530
Epoch: 2/100, Train Loss: 2.0763, Val PositionMAE: 5.0515
Epoch: 3/100, Train Loss: 2.0748, Val PositionMAE: 5.0504
Epoch: 4/100, Train Loss: 2.0745, Val PositionMAE: 5.0496
Epoch: 5/100, Train Loss: 2.0735, Val PositionMAE: 5.0489
Epoch: 6/100, Train Loss: 2.0732, Val PositionMAE: 5.0483
Epoch: 7/100, Train Loss: 2.0725, Val PositionMAE: 5.0479
Epoch: 8/100, Train Loss: 2.0729, Val PositionMAE: 5.0475
Epoch: 9/100, Train Loss: 2.0711, Val PositionMAE: 5.0472
Epoch: 10/100, Train Loss: 2.0712, Val PositionMAE: 5.0470
Epoch: 11/100, Train Loss: 2.0728, Val PositionMAE: 5.0468
Epoch: 12/100, Train Loss: 2.0712, Val PositionMAE: 5.0467
Epoch: 13/100, Train Loss: 2.0707, Val PositionMAE: 5.0466
Epoch: 14/100, Train Loss: 2.0706, Val PositionMAE: 5.0465
Epoch: 15/100, Train Loss: 2.0706, Val PositionMAE: 5.0465
Epoch: 16/100, Train Loss: 2.0697, Val PositionMAE: 5.0465
Epoch: 17/100, Train Loss: 2.0697, Val PositionMAE: 5.0465
Epoch: 18/100, Train Loss: 2.0698, Val PositionMAE: 5.0464
Epoch: 19/100, Train Loss: 2.0697, Val PositionMAE: 5.0465
Epoch: 20/100, Train Loss: 2.0704, Val PositionMAE: 5.0465
Epoch: 21/100, Train Loss: 2.0694, Val PositionMAE: 5.0465
Epoch: 22/100, Train Loss: 2.0699, Val PositionMAE: 5.0466
Epoch: 23/100, Train Loss: 2.0705, Val PositionMAE: 5.0466
Epoch: 24/100, Train Loss: 2.0695, Val PositionMAE: 5.0467
Epoch: 25/100, Train Loss: 2.0687, Val PositionMAE: 5.0467
Epoch: 26/100, Train Loss: 2.0683, Val PositionMAE: 5.0468
Epoch: 27/100, Train Loss: 2.0690, Val PositionMAE: 5.0468
Epoch: 28/100, Train Loss: 2.0686, Val PositionMAE: 5.0469
Maximum patience reached
Test PositionMAE: 5.0201

Running with seed: 44

Model Summary for MLP:
Total trainable parameters: 403,564 (404k)
Model architecture:
BaselineMLP(
  (model): Sequential(
    (0): Linear(in_features=6000, out_features=64, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.5, inplace=False)
    (3): Linear(in_features=64, out_features=300, bias=True)
  )
)
Epoch: 1/100, Train Loss: 2.0771, Val PositionMAE: 5.0529
Epoch: 2/100, Train Loss: 2.0751, Val PositionMAE: 5.0514
Epoch: 3/100, Train Loss: 2.0742, Val PositionMAE: 5.0503
Epoch: 4/100, Train Loss: 2.0731, Val PositionMAE: 5.0495
Epoch: 5/100, Train Loss: 2.0731, Val PositionMAE: 5.0488
Epoch: 6/100, Train Loss: 2.0728, Val PositionMAE: 5.0483
Epoch: 7/100, Train Loss: 2.0721, Val PositionMAE: 5.0478
Epoch: 8/100, Train Loss: 2.0715, Val PositionMAE: 5.0475
Epoch: 9/100, Train Loss: 2.0719, Val PositionMAE: 5.0472
Epoch: 10/100, Train Loss: 2.0716, Val PositionMAE: 5.0470
Epoch: 11/100, Train Loss: 2.0714, Val PositionMAE: 5.0468
Epoch: 12/100, Train Loss: 2.0718, Val PositionMAE: 5.0467
Epoch: 13/100, Train Loss: 2.0707, Val PositionMAE: 5.0466
Epoch: 14/100, Train Loss: 2.0710, Val PositionMAE: 5.0465
Epoch: 15/100, Train Loss: 2.0715, Val PositionMAE: 5.0465
Epoch: 16/100, Train Loss: 2.0701, Val PositionMAE: 5.0465
Epoch: 17/100, Train Loss: 2.0703, Val PositionMAE: 5.0465
Epoch: 18/100, Train Loss: 2.0690, Val PositionMAE: 5.0465
Epoch: 19/100, Train Loss: 2.0703, Val PositionMAE: 5.0465
Epoch: 20/100, Train Loss: 2.0703, Val PositionMAE: 5.0465
Epoch: 21/100, Train Loss: 2.0697, Val PositionMAE: 5.0466
Epoch: 22/100, Train Loss: 2.0692, Val PositionMAE: 5.0467
Epoch: 23/100, Train Loss: 2.0689, Val PositionMAE: 5.0467
Epoch: 24/100, Train Loss: 2.0692, Val PositionMAE: 5.0467
Epoch: 25/100, Train Loss: 2.0702, Val PositionMAE: 5.0468
Epoch: 26/100, Train Loss: 2.0684, Val PositionMAE: 5.0468
Epoch: 27/100, Train Loss: 2.0688, Val PositionMAE: 5.0469
Maximum patience reached
Test PositionMAE: 5.0197
Results saved to logs/CHILI-3K/AbsPositionRegressionxPDF/MLP_404k/results.csv

,Model,Dataset,Task,Seed,Train samples,Val samples,Test samples,Train time,Trainable parameters,Train loss,Metric name,Val metric,Test metric
0,MLP,CHILI-3K,AbsPositionRegressionxPDF,42,2031,255,255,95.260112,403564,2.068898,PositionMAE,5.046886,5.019817
1,MLP,CHILI-3K,AbsPositionRegressionxPDF,43,2031,255,255,97.629788,403564,2.068645,PositionMAE,5.046919,5.020097
2,MLP,CHILI-3K,AbsPositionRegressionxPDF,44,2031,255,255,92.557746,403564,2.068835,PositionMAE,5.046895,5.019716

In [2]:

# Path to your configuration file
config_path = "CHILI_mlp_config.yaml"

# Run the benchmark
results = run_benchmark_from_notebook(config_path, use_cpu=False)

# Display the results
results

Using device: cuda
Validating dataset (max atoms: 100)...
Dataset validation successful - all structures have appropriate atom counts.
Dataset: CHILI-3K
Task: AbsPositionRegressionxPDF
Model: MLP
Training samples: 2544
Validation samples: 318
Test samples: 318

Running with seed: 42
Epoch: 1/100, Train Loss: 10.1648, Val PositionMAE: 4.9127
Epoch: 2/100, Train Loss: 10.1280, Val PositionMAE: 4.9926
Epoch: 3/100, Train Loss: 10.1258, Val PositionMAE: 4.9433
Epoch: 4/100, Train Loss: 10.0894, Val PositionMAE: 4.9534
Epoch: 5/100, Train Loss: 10.1140, Val PositionMAE: 4.9858
Epoch: 6/100, Train Loss: 10.1012, Val PositionMAE: 4.9703
Epoch: 7/100, Train Loss: 10.0999, Val PositionMAE: 4.9573
Epoch: 8/100, Train Loss: 10.0951, Val PositionMAE: 4.9449
Epoch: 9/100, Train Loss: 10.1291, Val PositionMAE: 4.9459
Epoch: 10/100, Train Loss: 10.1046, Val PositionMAE: 4.9496
Epoch: 11/100, Train Loss: 10.1222, Val PositionMAE: 4.9735
Epoch: 12/100, Train Loss: 10.0911, Val PositionMAE: 4.9501
Epoch: 13/100, Train Loss: 10.1534, Val PositionMAE: 4.9648
Epoch: 14/100, Train Loss: 10.1215, Val PositionMAE: 4.9582
Epoch: 15/100, Train Loss: 10.1411, Val PositionMAE: 4.9439
Epoch: 16/100, Train Loss: 10.1389, Val PositionMAE: 4.9692
Epoch: 17/100, Train Loss: 10.0908, Val PositionMAE: 4.9496
Epoch: 18/100, Train Loss: 10.1388, Val PositionMAE: 4.9679
Epoch: 19/100, Train Loss: 10.0750, Val PositionMAE: 4.9746
Epoch: 20/100, Train Loss: 10.0793, Val PositionMAE: 4.9633
Epoch: 21/100, Train Loss: 10.1082, Val PositionMAE: 4.9542
Epoch: 22/100, Train Loss: 10.0839, Val PositionMAE: 4.9640
Epoch: 23/100, Train Loss: 10.0941, Val PositionMAE: 4.9638
Epoch: 24/100, Train Loss: 10.1015, Val PositionMAE: 4.9731
Epoch: 25/100, Train Loss: 10.1213, Val PositionMAE: 4.9644
Epoch: 26/100, Train Loss: 10.0876, Val PositionMAE: 4.9789
Epoch: 27/100, Train Loss: 10.1297, Val PositionMAE: 4.9695
Epoch: 28/100, Train Loss: 10.1244, Val PositionMAE: 4.9405
Epoch: 29/100, Train Loss: 10.1360, Val PositionMAE: 4.9676
Epoch: 30/100, Train Loss: 10.0843, Val PositionMAE: 4.9468
Epoch: 31/100, Train Loss: 10.1078, Val PositionMAE: 4.9638
Epoch: 32/100, Train Loss: 10.0751, Val PositionMAE: 4.9630
Epoch: 33/100, Train Loss: 10.0919, Val PositionMAE: 4.9608
Epoch: 34/100, Train Loss: 10.1135, Val PositionMAE: 4.9656
Epoch: 35/100, Train Loss: 10.1886, Val PositionMAE: 4.9444
Epoch: 36/100, Train Loss: 10.0864, Val PositionMAE: 4.9834
Epoch: 37/100, Train Loss: 10.1226, Val PositionMAE: 4.9644
Epoch: 38/100, Train Loss: 10.1080, Val PositionMAE: 4.9809
Epoch: 39/100, Train Loss: 10.0764, Val PositionMAE: 4.9570
Epoch: 40/100, Train Loss: 10.0614, Val PositionMAE: 4.9643
Epoch: 41/100, Train Loss: 10.0994, Val PositionMAE: 4.9852
Epoch: 42/100, Train Loss: 10.0680, Val PositionMAE: 4.9673
Epoch: 43/100, Train Loss: 10.0796, Val PositionMAE: 4.9623
Epoch: 44/100, Train Loss: 10.1636, Val PositionMAE: 4.9765
Epoch: 45/100, Train Loss: 10.1289, Val PositionMAE: 4.9642
Epoch: 46/100, Train Loss: 10.1935, Val PositionMAE: 4.9756
Epoch: 47/100, Train Loss: 10.1174, Val PositionMAE: 4.9515
Epoch: 48/100, Train Loss: 10.1073, Val PositionMAE: 4.9547
Epoch: 49/100, Train Loss: 10.0948, Val PositionMAE: 4.9556
Epoch: 50/100, Train Loss: 10.0934, Val PositionMAE: 4.9500
Epoch: 51/100, Train Loss: 10.1332, Val PositionMAE: 4.9743
Epoch: 52/100, Train Loss: 10.1101, Val PositionMAE: 4.9437
Epoch: 53/100, Train Loss: 10.1683, Val PositionMAE: 4.9546
Epoch: 54/100, Train Loss: 10.0910, Val PositionMAE: 4.9673
Epoch: 55/100, Train Loss: 10.0881, Val PositionMAE: 4.9693
Epoch: 56/100, Train Loss: 10.0636, Val PositionMAE: 4.9509
Epoch: 57/100, Train Loss: 10.1276, Val PositionMAE: 4.9497
Epoch: 58/100, Train Loss: 10.0825, Val PositionMAE: 4.9607
Epoch: 59/100, Train Loss: 10.1295, Val PositionMAE: 4.9646
Epoch: 60/100, Train Loss: 10.0962, Val PositionMAE: 4.9563
Epoch: 61/100, Train Loss: 10.1351, Val PositionMAE: 4.9546
Epoch: 62/100, Train Loss: 10.1531, Val PositionMAE: 4.9636
Epoch: 63/100, Train Loss: 10.1010, Val PositionMAE: 4.9652
Epoch: 64/100, Train Loss: 10.0611, Val PositionMAE: 4.9711
Epoch: 65/100, Train Loss: 10.0925, Val PositionMAE: 4.9643
Epoch: 66/100, Train Loss: 10.1004, Val PositionMAE: 4.9609
Epoch: 67/100, Train Loss: 10.1060, Val PositionMAE: 4.9626
Epoch: 68/100, Train Loss: 10.1043, Val PositionMAE: 4.9686
Epoch: 69/100, Train Loss: 10.1152, Val PositionMAE: 4.9615
Epoch: 70/100, Train Loss: 10.1223, Val PositionMAE: 4.9664
Epoch: 71/100, Train Loss: 10.1347, Val PositionMAE: 4.9634
Epoch: 72/100, Train Loss: 10.1188, Val PositionMAE: 4.9633
Epoch: 73/100, Train Loss: 10.1180, Val PositionMAE: 4.9708
Epoch: 74/100, Train Loss: 10.0853, Val PositionMAE: 4.9608
Epoch: 75/100, Train Loss: 10.0612, Val PositionMAE: 4.9714
Epoch: 76/100, Train Loss: 10.1206, Val PositionMAE: 4.9695
Epoch: 77/100, Train Loss: 10.0998, Val PositionMAE: 4.9700
Epoch: 78/100, Train Loss: 10.0808, Val PositionMAE: 4.9613
Epoch: 79/100, Train Loss: 10.1074, Val PositionMAE: 4.9635
Epoch: 80/100, Train Loss: 10.0614, Val PositionMAE: 4.9697
Epoch: 81/100, Train Loss: 10.1122, Val PositionMAE: 4.9658
Epoch: 82/100, Train Loss: 10.1098, Val PositionMAE: 4.9639
Epoch: 83/100, Train Loss: 10.1084, Val PositionMAE: 4.9675
Epoch: 84/100, Train Loss: 10.1019, Val PositionMAE: 4.9670
Epoch: 85/100, Train Loss: 10.0912, Val PositionMAE: 4.9685
Epoch: 86/100, Train Loss: 10.1270, Val PositionMAE: 4.9610
Epoch: 87/100, Train Loss: 10.0765, Val PositionMAE: 4.9643
Epoch: 88/100, Train Loss: 10.1173, Val PositionMAE: 4.9645
Epoch: 89/100, Train Loss: 10.1014, Val PositionMAE: 4.9688
Epoch: 90/100, Train Loss: 10.0688, Val PositionMAE: 4.9675
Epoch: 91/100, Train Loss: 10.1591, Val PositionMAE: 4.9611
Epoch: 92/100, Train Loss: 10.1050, Val PositionMAE: 4.9584
Epoch: 93/100, Train Loss: 10.1026, Val PositionMAE: 4.9674
Epoch: 94/100, Train Loss: 10.1199, Val PositionMAE: 4.9634
Epoch: 95/100, Train Loss: 10.0898, Val PositionMAE: 4.9625
Epoch: 96/100, Train Loss: 10.1072, Val PositionMAE: 4.9647
Epoch: 97/100, Train Loss: 10.0830, Val PositionMAE: 4.9711
Epoch: 98/100, Train Loss: 10.1124, Val PositionMAE: 4.9678
Epoch: 99/100, Train Loss: 10.0876, Val PositionMAE: 4.9589
Epoch: 100/100, Train Loss: 10.0823, Val PositionMAE: 4.9604
Test PositionMAE: 5.0351

Running with seed: 43
Epoch: 1/100, Train Loss: 10.1370, Val PositionMAE: 4.8807
Epoch: 2/100, Train Loss: 10.1292, Val PositionMAE: 4.9147
Epoch: 3/100, Train Loss: 10.0763, Val PositionMAE: 4.9949
Epoch: 4/100, Train Loss: 10.0477, Val PositionMAE: 4.9897
Epoch: 5/100, Train Loss: 10.1508, Val PositionMAE: 4.9324
Epoch: 6/100, Train Loss: 10.1194, Val PositionMAE: 4.9677
Epoch: 7/100, Train Loss: 10.1155, Val PositionMAE: 5.0606
Epoch: 8/100, Train Loss: 10.1232, Val PositionMAE: 4.9608
Epoch: 9/100, Train Loss: 10.1320, Val PositionMAE: 4.9608
Epoch: 10/100, Train Loss: 10.0927, Val PositionMAE: 4.9670
Epoch: 11/100, Train Loss: 10.1629, Val PositionMAE: 4.9482
Epoch: 12/100, Train Loss: 10.0913, Val PositionMAE: 4.9499
Epoch: 13/100, Train Loss: 10.1408, Val PositionMAE: 4.9394
Epoch: 14/100, Train Loss: 10.1054, Val PositionMAE: 4.9755
Epoch: 15/100, Train Loss: 10.0778, Val PositionMAE: 4.9401
Epoch: 16/100, Train Loss: 10.0924, Val PositionMAE: 4.9680
Epoch: 17/100, Train Loss: 10.0959, Val PositionMAE: 4.9633
Epoch: 18/100, Train Loss: 10.1114, Val PositionMAE: 4.9923
Epoch: 19/100, Train Loss: 10.0618, Val PositionMAE: 4.9310
Epoch: 20/100, Train Loss: 10.1251, Val PositionMAE: 4.9637
Epoch: 21/100, Train Loss: 10.0774, Val PositionMAE: 4.9548
Epoch: 22/100, Train Loss: 10.1683, Val PositionMAE: 4.9363
Epoch: 23/100, Train Loss: 10.1403, Val PositionMAE: 4.9544
Epoch: 24/100, Train Loss: 10.0765, Val PositionMAE: 4.9675
Epoch: 25/100, Train Loss: 10.1561, Val PositionMAE: 4.9789
Epoch: 26/100, Train Loss: 10.0800, Val PositionMAE: 4.9859
Epoch: 27/100, Train Loss: 10.1206, Val PositionMAE: 4.9385
Epoch: 28/100, Train Loss: 10.1076, Val PositionMAE: 4.9823
Epoch: 29/100, Train Loss: 10.1154, Val PositionMAE: 4.9660
Epoch: 30/100, Train Loss: 10.0965, Val PositionMAE: 4.9609
Epoch: 31/100, Train Loss: 10.1291, Val PositionMAE: 4.9655
Epoch: 32/100, Train Loss: 10.1043, Val PositionMAE: 4.9709
Epoch: 33/100, Train Loss: 10.0915, Val PositionMAE: 4.9538
Epoch: 34/100, Train Loss: 10.0885, Val PositionMAE: 4.9751
Epoch: 35/100, Train Loss: 10.1094, Val PositionMAE: 4.9651
Epoch: 36/100, Train Loss: 10.1221, Val PositionMAE: 4.9499
Epoch: 37/100, Train Loss: 10.1087, Val PositionMAE: 4.9607
Epoch: 38/100, Train Loss: 10.1120, Val PositionMAE: 4.9687
Epoch: 39/100, Train Loss: 10.1373, Val PositionMAE: 4.9503
Epoch: 40/100, Train Loss: 10.1030, Val PositionMAE: 4.9533
Epoch: 41/100, Train Loss: 10.0891, Val PositionMAE: 4.9757
Epoch: 42/100, Train Loss: 10.1038, Val PositionMAE: 4.9600
Epoch: 43/100, Train Loss: 10.1114, Val PositionMAE: 4.9719
Epoch: 44/100, Train Loss: 10.0756, Val PositionMAE: 4.9585
Epoch: 45/100, Train Loss: 10.1006, Val PositionMAE: 4.9523
Epoch: 46/100, Train Loss: 10.0679, Val PositionMAE: 4.9719
Epoch: 47/100, Train Loss: 10.1306, Val PositionMAE: 4.9691
Epoch: 48/100, Train Loss: 10.0908, Val PositionMAE: 4.9607
Epoch: 49/100, Train Loss: 10.0851, Val PositionMAE: 4.9701
Epoch: 50/100, Train Loss: 10.1329, Val PositionMAE: 4.9741
Epoch: 51/100, Train Loss: 10.0929, Val PositionMAE: 4.9523
Epoch: 52/100, Train Loss: 10.1503, Val PositionMAE: 4.9646
Epoch: 53/100, Train Loss: 10.1380, Val PositionMAE: 4.9612
Epoch: 54/100, Train Loss: 10.1341, Val PositionMAE: 4.9598
Epoch: 55/100, Train Loss: 10.1155, Val PositionMAE: 4.9574
Epoch: 56/100, Train Loss: 10.1162, Val PositionMAE: 4.9639
Epoch: 57/100, Train Loss: 10.1078, Val PositionMAE: 4.9670
Epoch: 58/100, Train Loss: 10.0906, Val PositionMAE: 4.9583
Epoch: 59/100, Train Loss: 10.0744, Val PositionMAE: 4.9606
Epoch: 60/100, Train Loss: 10.1042, Val PositionMAE: 4.9666
Epoch: 61/100, Train Loss: 10.1258, Val PositionMAE: 4.9624
Epoch: 62/100, Train Loss: 10.1342, Val PositionMAE: 4.9714
Epoch: 63/100, Train Loss: 10.0889, Val PositionMAE: 4.9585
Epoch: 64/100, Train Loss: 10.1084, Val PositionMAE: 4.9703
Epoch: 65/100, Train Loss: 10.0977, Val PositionMAE: 4.9699
Epoch: 66/100, Train Loss: 10.1249, Val PositionMAE: 4.9587
Epoch: 67/100, Train Loss: 10.1325, Val PositionMAE: 4.9614
Epoch: 68/100, Train Loss: 10.1224, Val PositionMAE: 4.9651
Epoch: 69/100, Train Loss: 10.1286, Val PositionMAE: 4.9608
Epoch: 70/100, Train Loss: 10.1205, Val PositionMAE: 4.9657
Epoch: 71/100, Train Loss: 10.1236, Val PositionMAE: 4.9681
Epoch: 72/100, Train Loss: 10.1470, Val PositionMAE: 4.9680
Epoch: 73/100, Train Loss: 10.1624, Val PositionMAE: 4.9668
Epoch: 74/100, Train Loss: 10.1606, Val PositionMAE: 4.9631
Epoch: 75/100, Train Loss: 10.1800, Val PositionMAE: 4.9674
Epoch: 76/100, Train Loss: 10.1141, Val PositionMAE: 4.9700
Epoch: 77/100, Train Loss: 10.1205, Val PositionMAE: 4.9667
Epoch: 78/100, Train Loss: 10.1377, Val PositionMAE: 4.9728
Epoch: 79/100, Train Loss: 10.1046, Val PositionMAE: 4.9680
Epoch: 80/100, Train Loss: 10.1037, Val PositionMAE: 4.9683
Epoch: 81/100, Train Loss: 10.1340, Val PositionMAE: 4.9681
Epoch: 82/100, Train Loss: 10.0730, Val PositionMAE: 4.9658
Epoch: 83/100, Train Loss: 10.1280, Val PositionMAE: 4.9596
Epoch: 84/100, Train Loss: 10.1135, Val PositionMAE: 4.9623
Epoch: 85/100, Train Loss: 10.1161, Val PositionMAE: 4.9613
Epoch: 86/100, Train Loss: 10.0669, Val PositionMAE: 4.9649
Epoch: 87/100, Train Loss: 10.1017, Val PositionMAE: 4.9621
Epoch: 88/100, Train Loss: 10.1177, Val PositionMAE: 4.9614
Epoch: 89/100, Train Loss: 10.1002, Val PositionMAE: 4.9693
Epoch: 90/100, Train Loss: 10.0985, Val PositionMAE: 4.9708
Epoch: 91/100, Train Loss: 10.1395, Val PositionMAE: 4.9663
Epoch: 92/100, Train Loss: 10.1289, Val PositionMAE: 4.9732
Epoch: 93/100, Train Loss: 10.1113, Val PositionMAE: 4.9667
Epoch: 94/100, Train Loss: 10.1225, Val PositionMAE: 4.9674
Epoch: 95/100, Train Loss: 10.1022, Val PositionMAE: 4.9687
Epoch: 96/100, Train Loss: 10.1641, Val PositionMAE: 4.9672
Epoch: 97/100, Train Loss: 10.1085, Val PositionMAE: 4.9692
Epoch: 98/100, Train Loss: 10.1007, Val PositionMAE: 4.9707
Epoch: 99/100, Train Loss: 10.0828, Val PositionMAE: 4.9666
Epoch: 100/100, Train Loss: 10.0895, Val PositionMAE: 4.9596
Test PositionMAE: 5.0058

Running with seed: 44
Epoch: 1/100, Train Loss: 10.1628, Val PositionMAE: 4.9140
Epoch: 2/100, Train Loss: 10.1256, Val PositionMAE: 4.8909
Epoch: 3/100, Train Loss: 10.0884, Val PositionMAE: 4.8926
Epoch: 4/100, Train Loss: 10.0855, Val PositionMAE: 5.1051
Epoch: 5/100, Train Loss: 9.9590, Val PositionMAE: 5.7674
Epoch: 6/100, Train Loss: 10.2066, Val PositionMAE: 4.8747
Epoch: 7/100, Train Loss: 10.1063, Val PositionMAE: 4.8768
Epoch: 8/100, Train Loss: 10.1091, Val PositionMAE: 4.8752
Epoch: 9/100, Train Loss: 9.9711, Val PositionMAE: 5.9499
Epoch: 10/100, Train Loss: 9.0718, Val PositionMAE: 7.9932
Epoch: 11/100, Train Loss: 9.6335, Val PositionMAE: 4.8709
Epoch: 12/100, Train Loss: 10.1577, Val PositionMAE: 4.8729
Epoch: 13/100, Train Loss: 10.1268, Val PositionMAE: 4.8757
Epoch: 14/100, Train Loss: 10.1013, Val PositionMAE: 4.8829
Epoch: 15/100, Train Loss: 10.1196, Val PositionMAE: 4.8850
Epoch: 16/100, Train Loss: 10.1400, Val PositionMAE: 4.8770
Epoch: 17/100, Train Loss: 10.1333, Val PositionMAE: 4.8877
Epoch: 18/100, Train Loss: 10.1237, Val PositionMAE: 4.8991
Epoch: 19/100, Train Loss: 10.1043, Val PositionMAE: 4.8908
Epoch: 20/100, Train Loss: 10.1116, Val PositionMAE: 4.9198
Epoch: 21/100, Train Loss: 10.1190, Val PositionMAE: 4.8897
Epoch: 22/100, Train Loss: 10.0984, Val PositionMAE: 4.9341
Epoch: 23/100, Train Loss: 10.0476, Val PositionMAE: 4.9187
Epoch: 24/100, Train Loss: 10.1144, Val PositionMAE: 4.9285
Epoch: 25/100, Train Loss: 10.0724, Val PositionMAE: 4.9872
Epoch: 26/100, Train Loss: 10.0795, Val PositionMAE: 4.9892
Epoch: 27/100, Train Loss: 10.0249, Val PositionMAE: 5.0229
Epoch: 28/100, Train Loss: 10.0629, Val PositionMAE: 5.0051
Epoch: 29/100, Train Loss: 9.9705, Val PositionMAE: 5.0502
Epoch: 30/100, Train Loss: 10.0354, Val PositionMAE: 5.7758
Epoch: 31/100, Train Loss: 9.8627, Val PositionMAE: 4.8814
Epoch: 32/100, Train Loss: 10.1417, Val PositionMAE: 5.0840
Epoch: 33/100, Train Loss: 10.0234, Val PositionMAE: 5.1295
Epoch: 34/100, Train Loss: 10.2522, Val PositionMAE: 4.9597
Epoch: 35/100, Train Loss: 10.1535, Val PositionMAE: 4.9629
Epoch: 36/100, Train Loss: 10.1211, Val PositionMAE: 4.9631
Epoch: 37/100, Train Loss: 10.1152, Val PositionMAE: 4.9474
Epoch: 38/100, Train Loss: 10.1315, Val PositionMAE: 4.9497
Epoch: 39/100, Train Loss: 10.1238, Val PositionMAE: 4.9343
Epoch: 40/100, Train Loss: 10.1159, Val PositionMAE: 4.9425
Epoch: 41/100, Train Loss: 10.1484, Val PositionMAE: 4.9653
Epoch: 42/100, Train Loss: 10.1209, Val PositionMAE: 4.9428
Epoch: 43/100, Train Loss: 10.0770, Val PositionMAE: 4.9684
Epoch: 44/100, Train Loss: 10.1122, Val PositionMAE: 4.9530
Epoch: 45/100, Train Loss: 10.1457, Val PositionMAE: 4.9491
Epoch: 46/100, Train Loss: 10.1338, Val PositionMAE: 4.9263
Epoch: 47/100, Train Loss: 10.1379, Val PositionMAE: 4.9523
Epoch: 48/100, Train Loss: 10.1219, Val PositionMAE: 4.9518
Epoch: 49/100, Train Loss: 10.1770, Val PositionMAE: 4.9547
Epoch: 50/100, Train Loss: 10.1051, Val PositionMAE: 4.9499
Epoch: 51/100, Train Loss: 10.1085, Val PositionMAE: 4.9508
Epoch: 52/100, Train Loss: 10.0770, Val PositionMAE: 4.9608
Epoch: 53/100, Train Loss: 10.0805, Val PositionMAE: 4.9462
Epoch: 54/100, Train Loss: 10.0761, Val PositionMAE: 4.9594
Epoch: 55/100, Train Loss: 10.1367, Val PositionMAE: 4.9479
Epoch: 56/100, Train Loss: 10.1402, Val PositionMAE: 4.9716
Epoch: 57/100, Train Loss: 10.0956, Val PositionMAE: 4.9617
Epoch: 58/100, Train Loss: 10.1060, Val PositionMAE: 4.9728
Epoch: 59/100, Train Loss: 10.1406, Val PositionMAE: 4.9635
Epoch: 60/100, Train Loss: 10.1083, Val PositionMAE: 4.9572
Epoch: 61/100, Train Loss: 10.0738, Val PositionMAE: 4.9689
Epoch: 62/100, Train Loss: 10.0747, Val PositionMAE: 4.9757
Epoch: 63/100, Train Loss: 10.1174, Val PositionMAE: 4.9555
Epoch: 64/100, Train Loss: 10.1321, Val PositionMAE: 4.9536
Epoch: 65/100, Train Loss: 10.0808, Val PositionMAE: 4.9621
Epoch: 66/100, Train Loss: 10.1269, Val PositionMAE: 4.9521
Epoch: 67/100, Train Loss: 10.1609, Val PositionMAE: 4.9596
Epoch: 68/100, Train Loss: 10.0853, Val PositionMAE: 4.9576
Epoch: 69/100, Train Loss: 10.1422, Val PositionMAE: 4.9472
Epoch: 70/100, Train Loss: 10.1132, Val PositionMAE: 4.9566
Epoch: 71/100, Train Loss: 10.1678, Val PositionMAE: 4.9550
Epoch: 72/100, Train Loss: 10.0773, Val PositionMAE: 4.9657
Epoch: 73/100, Train Loss: 10.1355, Val PositionMAE: 4.9542
Epoch: 74/100, Train Loss: 10.0839, Val PositionMAE: 4.9618
Epoch: 75/100, Train Loss: 10.1297, Val PositionMAE: 4.9576
Epoch: 76/100, Train Loss: 10.1319, Val PositionMAE: 4.9371
Epoch: 77/100, Train Loss: 10.0777, Val PositionMAE: 4.9528
Epoch: 78/100, Train Loss: 10.1573, Val PositionMAE: 4.9566
Epoch: 79/100, Train Loss: 10.1138, Val PositionMAE: 4.9610
Epoch: 80/100, Train Loss: 10.1105, Val PositionMAE: 4.9726
Epoch: 81/100, Train Loss: 10.0991, Val PositionMAE: 4.9587
Epoch: 82/100, Train Loss: 10.0850, Val PositionMAE: 4.9570
Epoch: 83/100, Train Loss: 10.1227, Val PositionMAE: 4.9536
Epoch: 84/100, Train Loss: 10.1219, Val PositionMAE: 4.9587
Epoch: 85/100, Train Loss: 10.0837, Val PositionMAE: 4.9537
Epoch: 86/100, Train Loss: 10.1678, Val PositionMAE: 4.9601
Epoch: 87/100, Train Loss: 10.0623, Val PositionMAE: 4.9551
Epoch: 88/100, Train Loss: 10.0856, Val PositionMAE: 4.9579
Epoch: 89/100, Train Loss: 10.1224, Val PositionMAE: 4.9535
Epoch: 90/100, Train Loss: 10.0788, Val PositionMAE: 4.9544
Epoch: 91/100, Train Loss: 10.1278, Val PositionMAE: 4.9455
Epoch: 92/100, Train Loss: 10.0804, Val PositionMAE: 4.9611
Epoch: 93/100, Train Loss: 10.0837, Val PositionMAE: 4.9449
Epoch: 94/100, Train Loss: 10.1075, Val PositionMAE: 4.9613
Epoch: 95/100, Train Loss: 10.1107, Val PositionMAE: 4.9512
Epoch: 96/100, Train Loss: 10.1346, Val PositionMAE: 4.9508
Epoch: 97/100, Train Loss: 10.0877, Val PositionMAE: 4.9703
Epoch: 98/100, Train Loss: 10.0830, Val PositionMAE: 4.9578
Epoch: 99/100, Train Loss: 10.0950, Val PositionMAE: 4.9613
Epoch: 100/100, Train Loss: 10.1028, Val PositionMAE: 4.9514
Test PositionMAE: 4.9960

Running with seed: 45
Epoch: 1/100, Train Loss: 10.1177, Val PositionMAE: 4.9339
Epoch: 2/100, Train Loss: 10.1422, Val PositionMAE: 4.8964
Epoch: 3/100, Train Loss: 10.0921, Val PositionMAE: 4.9471
Epoch: 4/100, Train Loss: 10.1430, Val PositionMAE: 4.9388
Epoch: 5/100, Train Loss: 10.0655, Val PositionMAE: 4.9564
Epoch: 6/100, Train Loss: 10.1632, Val PositionMAE: 4.9709
Epoch: 7/100, Train Loss: 10.1294, Val PositionMAE: 4.9622
Epoch: 8/100, Train Loss: 10.1549, Val PositionMAE: 4.9763
Epoch: 9/100, Train Loss: 10.1506, Val PositionMAE: 4.9923
Epoch: 10/100, Train Loss: 10.0735, Val PositionMAE: 4.9566
Epoch: 11/100, Train Loss: 10.1557, Val PositionMAE: 4.9440
Epoch: 12/100, Train Loss: 10.0950, Val PositionMAE: 4.9436
Epoch: 13/100, Train Loss: 10.1033, Val PositionMAE: 4.9747
Epoch: 14/100, Train Loss: 10.1127, Val PositionMAE: 4.9632
Epoch: 15/100, Train Loss: 10.1187, Val PositionMAE: 4.9648
Epoch: 16/100, Train Loss: 10.1296, Val PositionMAE: 4.9279
Epoch: 17/100, Train Loss: 10.1030, Val PositionMAE: 4.9755
Epoch: 18/100, Train Loss: 10.1167, Val PositionMAE: 4.9294
Epoch: 19/100, Train Loss: 10.1076, Val PositionMAE: 4.9480
Epoch: 20/100, Train Loss: 10.0842, Val PositionMAE: 4.9297
Epoch: 21/100, Train Loss: 10.1058, Val PositionMAE: 4.9825
Epoch: 22/100, Train Loss: 10.1046, Val PositionMAE: 4.9572
Epoch: 23/100, Train Loss: 10.1126, Val PositionMAE: 4.9780
Epoch: 24/100, Train Loss: 10.0721, Val PositionMAE: 4.9572
Epoch: 25/100, Train Loss: 10.1100, Val PositionMAE: 4.9396
Epoch: 26/100, Train Loss: 10.1466, Val PositionMAE: 4.9830

,Model,Dataset,Task,Seed,Train samples,Val samples,Test samples,Train time,Trainable parameters,Train loss,Metric name,Val metric,Test metric
0,MLP,CHILI-3K,AbsPositionRegressionxPDF,42,2544,318,318,506.012601,856364,10.082343,PositionMAE,4.960412,5.035127
1,MLP,CHILI-3K,AbsPositionRegressionxPDF,43,2544,318,318,505.101501,856364,10.089471,PositionMAE,4.959578,5.005806
2,MLP,CHILI-3K,AbsPositionRegressionxPDF,44,2544,318,318,506.070427,856364,10.102758,PositionMAE,4.951415,4.995952
3,MLP,CHILI-3K,AbsPositionRegressionxPDF,45,2544,318,318,505.836004,856364,10.102538,PositionMAE,4.968874,5.021694
4,MLP,CHILI-3K,AbsPositionRegressionxPDF,46,2544,318,318,505.516973,856364,10.093667,PositionMAE,4.959649,5.016514