In [1]:
from test_vectordiff_overfitting import run_benchmark_overfitting

In [2]:
run_benchmark_overfitting(config_path='./configs/vector_diff_config.yaml')

Using device: cuda
Created small dataset with 5 samples
Validating dataset (max atoms: 100)...
Dataset validation successful - all structures have appropriate atom counts.
Dataset: CHILI-3K (Small subset for overfitting test)
Task: AbsPositionRegressionxPDF
Model: VectorDiffusion
Training samples: 4
Validation samples: 1

Running with seed: 42

Model Summary for VectorDiffusion:
Total trainable parameters: 12,433,667 (12434k)
Model architecture:
VectorDiffusion(
  (encoder): Encoder(
    (encoder): Sequential(
      (0): Linear(in_features=6000, out_features=256, bias=True)
      (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Dropout(p=0.1, inplace=False)
      (4): Linear(in_features=256, out_features=256, bias=True)
      (5): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (6): Identity()
      (7): Identity()
    )
  )
  (denoiser): VectorPosNet(
    (time_embedding): Sequential(
      (0): Linear(in_features=1, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
      (4): Linear(in_features=256, out_features=256, bias=True)
    )
    (cond_embedding): Sequential(
      (0): Linear(in_features=256, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
      (4): Linear(in_features=256, out_features=256, bias=True)
    )
    (input_proj): Linear(in_features=3, out_features=256, bias=True)
    (down1): Sequential(
      (0): Linear(in_features=256, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
    )
    (pool1): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down2): Sequential(
      (0): Linear(in_features=256, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=512, bias=True)
      (3): ReLU()
    )
    (pool2): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down3): Sequential(
      (0): Linear(in_features=512, out_features=512, bias=True)
      (1): ReLU()
      (2): Linear(in_features=512, out_features=1024, bias=True)
      (3): ReLU()
    )
    (pool3): AvgPool1d(kernel_size=(5,), stride=(5,), padding=(0,))
    (bottleneck): Sequential(
      (0): Linear(in_features=1280, out_features=1024, bias=True)
      (1): ReLU()
      (2): Linear(in_features=1024, out_features=1024, bias=True)
      (3): ReLU()
    )
    (up3): Linear(in_features=1024, out_features=5120, bias=True)
    (up3_conv): Sequential(
      (0): Linear(in_features=1024, out_features=512, bias=True)
      (1): ReLU()
      (2): Linear(in_features=512, out_features=512, bias=True)
      (3): ReLU()
    )
    (up2): Linear(in_features=512, out_features=1024, bias=True)
    (up2_conv): Sequential(
      (0): Linear(in_features=512, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
    )
    (up1): Linear(in_features=256, out_features=512, bias=True)
    (up1_conv): Sequential(
      (0): Linear(in_features=256, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
    )
    (output_proj): Linear(in_features=256, out_features=3, bias=True)
  )
)
Epoch: 1/100, Train Loss: 0.5285, Val PositionMAE: 3.5434
Epoch: 2/100, Train Loss: 0.5328, Val PositionMAE: 3.2698
Epoch: 3/100, Train Loss: 0.5388, Val PositionMAE: 3.7001
Epoch: 4/100, Train Loss: 0.5179, Val PositionMAE: 3.5393
Epoch: 5/100, Train Loss: 0.5189, Val PositionMAE: 3.6005
Epoch: 6/100, Train Loss: 0.5003, Val PositionMAE: 3.2415
Epoch: 7/100, Train Loss: 0.5083, Val PositionMAE: 3.5299
Epoch: 8/100, Train Loss: 0.5265, Val PositionMAE: 3.3445
Epoch: 9/100, Train Loss: 0.5197, Val PositionMAE: 3.6950
Epoch: 10/100, Train Loss: 0.5106, Val PositionMAE: 3.2052
Epoch: 11/100, Train Loss: 0.5302, Val PositionMAE: 3.5185
Epoch: 12/100, Train Loss: 0.5326, Val PositionMAE: 3.6698
Epoch: 13/100, Train Loss: 0.5182, Val PositionMAE: 3.5865
Epoch: 14/100, Train Loss: 0.5014, Val PositionMAE: 3.2316
Epoch: 15/100, Train Loss: 0.5239, Val PositionMAE: 3.7308
Epoch: 16/100, Train Loss: 0.5081, Val PositionMAE: 3.2660
Epoch: 17/100, Train Loss: 0.5278, Val PositionMAE: 3.2941
Epoch: 18/100, Train Loss: 0.5299, Val PositionMAE: 3.3917
Epoch: 19/100, Train Loss: 0.5265, Val PositionMAE: 3.5638
Epoch: 20/100, Train Loss: 0.4992, Val PositionMAE: 3.7950
Epoch: 21/100, Train Loss: 0.5376, Val PositionMAE: 3.5536
Epoch: 22/100, Train Loss: 0.5526, Val PositionMAE: 3.6462
Epoch: 23/100, Train Loss: 0.5364, Val PositionMAE: 3.4745
Epoch: 24/100, Train Loss: 0.5236, Val PositionMAE: 3.5680
Epoch: 25/100, Train Loss: 0.5304, Val PositionMAE: 3.6022
Epoch: 26/100, Train Loss: 0.5519, Val PositionMAE: 3.3368
Epoch: 27/100, Train Loss: 0.5358, Val PositionMAE: 3.7928
Epoch: 28/100, Train Loss: 0.5457, Val PositionMAE: 3.4240
Epoch: 29/100, Train Loss: 0.5234, Val PositionMAE: 3.3533
Epoch: 30/100, Train Loss: 0.4992, Val PositionMAE: 3.3601
Epoch: 31/100, Train Loss: 0.5560, Val PositionMAE: 3.5350
Epoch: 32/100, Train Loss: 0.5407, Val PositionMAE: 3.4864
Epoch: 33/100, Train Loss: 0.5427, Val PositionMAE: 3.3979
Epoch: 34/100, Train Loss: 0.5378, Val PositionMAE: 3.5733
Epoch: 35/100, Train Loss: 0.5222, Val PositionMAE: 3.7037
Epoch: 36/100, Train Loss: 0.5145, Val PositionMAE: 3.5564
Epoch: 37/100, Train Loss: 0.5660, Val PositionMAE: 3.2648
Epoch: 38/100, Train Loss: 0.5409, Val PositionMAE: 3.7646
Epoch: 39/100, Train Loss: 0.5369, Val PositionMAE: 3.7333
Epoch: 40/100, Train Loss: 0.5336, Val PositionMAE: 3.4933
Maximum patience reached

Training completed in 25.38 seconds
Best validation PositionMAE: 3.2052
Results saved to ./logs/overfitting_test/VectorDiffusion_12434k_h256_T100/seed42
Results saved to ./logs/overfitting_test/VectorDiffusion_12434k_h256_T100/seed42\results/overfitting_results.csv

,Model,Dataset,Task,Seed,Train samples,Val samples,Train time,Trainable parameters,Train loss,Metric name,Val metric
0,VectorDiffusion,CHILI-3K (5 samples),AbsPositionRegressionxPDF,42,4,1,25.384309,12433667,0.533575,PositionMAE,3.20519

In [3]:
run_benchmark_overfitting(config_path='./configs/vector_diff_small_config.yaml')

Using device: cuda
Created small dataset with 5 samples
Validating dataset (max atoms: 100)...
Dataset validation successful - all structures have appropriate atom counts.
Dataset: CHILI-3K (Small subset for overfitting test)
Task: AbsPositionRegressionxPDF
Model: VectorDiffusion
Training samples: 4
Validation samples: 1

Running with seed: 42

Model Summary for VectorDiffusion:
Total trainable parameters: 1,068,611 (1069k)
Model architecture:
VectorDiffusion(
  (encoder): Encoder(
    (encoder): Sequential(
      (0): Linear(in_features=6000, out_features=64, bias=True)
      (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Dropout(p=0.1, inplace=False)
      (4): Linear(in_features=64, out_features=64, bias=True)
      (5): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (6): Identity()
      (7): Identity()
    )
  )
  (denoiser): VectorPosNet(
    (time_embedding): Sequential(
      (0): Linear(in_features=1, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
      (4): Linear(in_features=64, out_features=64, bias=True)
    )
    (cond_embedding): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
      (4): Linear(in_features=64, out_features=64, bias=True)
    )
    (input_proj): Linear(in_features=3, out_features=64, bias=True)
    (down1): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (pool1): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down2): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=128, bias=True)
      (3): ReLU()
    )
    (pool2): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down3): Sequential(
      (0): Linear(in_features=128, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=256, bias=True)
      (3): ReLU()
    )
    (pool3): AvgPool1d(kernel_size=(5,), stride=(5,), padding=(0,))
    (bottleneck): Sequential(
      (0): Linear(in_features=320, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
    )
    (up3): Linear(in_features=256, out_features=1280, bias=True)
    (up3_conv): Sequential(
      (0): Linear(in_features=256, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=128, bias=True)
      (3): ReLU()
    )
    (up2): Linear(in_features=128, out_features=256, bias=True)
    (up2_conv): Sequential(
      (0): Linear(in_features=128, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (up1): Linear(in_features=64, out_features=128, bias=True)
    (up1_conv): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (output_proj): Linear(in_features=64, out_features=3, bias=True)
  )
)
Epoch: 1/200, Train Loss: 1.5937, Val PositionMAE: 4.5112
Epoch: 2/200, Train Loss: 1.5792, Val PositionMAE: 4.4387
Epoch: 3/200, Train Loss: 1.6098, Val PositionMAE: 4.4808
Epoch: 4/200, Train Loss: 1.5819, Val PositionMAE: 4.6113
Epoch: 5/200, Train Loss: 1.6303, Val PositionMAE: 4.5654
Epoch: 6/200, Train Loss: 1.6269, Val PositionMAE: 4.4694
Epoch: 7/200, Train Loss: 1.6149, Val PositionMAE: 4.4066
Epoch: 8/200, Train Loss: 1.6478, Val PositionMAE: 4.5344
Epoch: 9/200, Train Loss: 1.6295, Val PositionMAE: 4.5784
Epoch: 10/200, Train Loss: 1.5711, Val PositionMAE: 4.4176
Epoch: 11/200, Train Loss: 1.5942, Val PositionMAE: 4.2380
Epoch: 12/200, Train Loss: 1.6119, Val PositionMAE: 4.3218
Epoch: 13/200, Train Loss: 1.6101, Val PositionMAE: 4.4927
Epoch: 14/200, Train Loss: 1.5485, Val PositionMAE: 4.6239
Epoch: 15/200, Train Loss: 1.6069, Val PositionMAE: 4.5756
Epoch: 16/200, Train Loss: 1.5760, Val PositionMAE: 4.4382
Epoch: 17/200, Train Loss: 1.5850, Val PositionMAE: 4.2976
Epoch: 18/200, Train Loss: 1.5707, Val PositionMAE: 4.3169
Epoch: 19/200, Train Loss: 1.5701, Val PositionMAE: 4.4030
Epoch: 20/200, Train Loss: 1.5867, Val PositionMAE: 4.6120
Epoch: 21/200, Train Loss: 1.6369, Val PositionMAE: 4.4386
Epoch: 22/200, Train Loss: 1.6651, Val PositionMAE: 4.4655
Epoch: 23/200, Train Loss: 1.5896, Val PositionMAE: 4.4376
Epoch: 24/200, Train Loss: 1.6037, Val PositionMAE: 4.4303
Epoch: 25/200, Train Loss: 1.6056, Val PositionMAE: 4.3104
Epoch: 26/200, Train Loss: 1.6250, Val PositionMAE: 4.4027
Epoch: 27/200, Train Loss: 1.5968, Val PositionMAE: 4.3482
Epoch: 28/200, Train Loss: 1.6061, Val PositionMAE: 4.4248
Epoch: 29/200, Train Loss: 1.6566, Val PositionMAE: 4.4178
Epoch: 30/200, Train Loss: 1.5743, Val PositionMAE: 4.6612
Epoch: 31/200, Train Loss: 1.5963, Val PositionMAE: 4.2626
Epoch: 32/200, Train Loss: 1.6266, Val PositionMAE: 4.2975
Epoch: 33/200, Train Loss: 1.5446, Val PositionMAE: 4.3454
Epoch: 34/200, Train Loss: 1.6131, Val PositionMAE: 4.3098
Epoch: 35/200, Train Loss: 1.5983, Val PositionMAE: 4.2908
Epoch: 36/200, Train Loss: 1.5864, Val PositionMAE: 4.5210
Epoch: 37/200, Train Loss: 1.5964, Val PositionMAE: 4.5474
Epoch: 38/200, Train Loss: 1.5816, Val PositionMAE: 4.4014
Epoch: 39/200, Train Loss: 1.5982, Val PositionMAE: 4.6011
Epoch: 40/200, Train Loss: 1.5757, Val PositionMAE: 4.3954
Epoch: 41/200, Train Loss: 1.6398, Val PositionMAE: 4.1816
Epoch: 42/200, Train Loss: 1.6043, Val PositionMAE: 4.5820
Epoch: 43/200, Train Loss: 1.6413, Val PositionMAE: 4.5486
Epoch: 44/200, Train Loss: 1.5796, Val PositionMAE: 4.4074
Epoch: 45/200, Train Loss: 1.6090, Val PositionMAE: 4.4367
Epoch: 46/200, Train Loss: 1.6140, Val PositionMAE: 4.6055
Epoch: 47/200, Train Loss: 1.6294, Val PositionMAE: 4.4933
Epoch: 48/200, Train Loss: 1.6114, Val PositionMAE: 4.5016
Epoch: 49/200, Train Loss: 1.6120, Val PositionMAE: 4.4456
Epoch: 50/200, Train Loss: 1.6187, Val PositionMAE: 4.3355
Epoch: 51/200, Train Loss: 1.6175, Val PositionMAE: 4.6777
Epoch: 52/200, Train Loss: 1.6046, Val PositionMAE: 4.5653
Epoch: 53/200, Train Loss: 1.6429, Val PositionMAE: 4.4859
Epoch: 54/200, Train Loss: 1.6131, Val PositionMAE: 4.6122
Epoch: 55/200, Train Loss: 1.6103, Val PositionMAE: 4.2342
Epoch: 56/200, Train Loss: 1.5870, Val PositionMAE: 4.2858
Epoch: 57/200, Train Loss: 1.5668, Val PositionMAE: 4.4474
Epoch: 58/200, Train Loss: 1.5607, Val PositionMAE: 4.4394
Epoch: 59/200, Train Loss: 1.5824, Val PositionMAE: 4.2963
Epoch: 60/200, Train Loss: 1.6183, Val PositionMAE: 4.3160
Epoch: 61/200, Train Loss: 1.5719, Val PositionMAE: 4.4028
Epoch: 62/200, Train Loss: 1.5979, Val PositionMAE: 4.3801
Epoch: 63/200, Train Loss: 1.6117, Val PositionMAE: 4.1850
Epoch: 64/200, Train Loss: 1.5796, Val PositionMAE: 4.4241
Epoch: 65/200, Train Loss: 1.5863, Val PositionMAE: 4.5863
Epoch: 66/200, Train Loss: 1.5995, Val PositionMAE: 4.4260
Epoch: 67/200, Train Loss: 1.6221, Val PositionMAE: 4.5043
Epoch: 68/200, Train Loss: 1.6637, Val PositionMAE: 4.5917
Epoch: 69/200, Train Loss: 1.5503, Val PositionMAE: 4.4444
Epoch: 70/200, Train Loss: 1.5910, Val PositionMAE: 4.4559
Epoch: 71/200, Train Loss: 1.6414, Val PositionMAE: 4.5116
Maximum patience reached

Training completed in 17.77 seconds
Best validation PositionMAE: 4.1816
Results saved to ./logs/overfitting_test/VectorDiffusion_1069k_h64_T50/seed42

Running with seed: 43

Model Summary for VectorDiffusion:
Total trainable parameters: 1,068,611 (1069k)
Model architecture:
VectorDiffusion(
  (encoder): Encoder(
    (encoder): Sequential(
      (0): Linear(in_features=6000, out_features=64, bias=True)
      (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Dropout(p=0.1, inplace=False)
      (4): Linear(in_features=64, out_features=64, bias=True)
      (5): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (6): Identity()
      (7): Identity()
    )
  )
  (denoiser): VectorPosNet(
    (time_embedding): Sequential(
      (0): Linear(in_features=1, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
      (4): Linear(in_features=64, out_features=64, bias=True)
    )
    (cond_embedding): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
      (4): Linear(in_features=64, out_features=64, bias=True)
    )
    (input_proj): Linear(in_features=3, out_features=64, bias=True)
    (down1): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (pool1): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down2): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=128, bias=True)
      (3): ReLU()
    )
    (pool2): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down3): Sequential(
      (0): Linear(in_features=128, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=256, bias=True)
      (3): ReLU()
    )
    (pool3): AvgPool1d(kernel_size=(5,), stride=(5,), padding=(0,))
    (bottleneck): Sequential(
      (0): Linear(in_features=320, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
    )
    (up3): Linear(in_features=256, out_features=1280, bias=True)
    (up3_conv): Sequential(
      (0): Linear(in_features=256, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=128, bias=True)
      (3): ReLU()
    )
    (up2): Linear(in_features=128, out_features=256, bias=True)
    (up2_conv): Sequential(
      (0): Linear(in_features=128, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (up1): Linear(in_features=64, out_features=128, bias=True)
    (up1_conv): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (output_proj): Linear(in_features=64, out_features=3, bias=True)
  )
)
Epoch: 1/200, Train Loss: 1.5931, Val PositionMAE: 4.6272
Epoch: 2/200, Train Loss: 1.5850, Val PositionMAE: 4.2431
Epoch: 3/200, Train Loss: 1.5758, Val PositionMAE: 4.5201
Epoch: 4/200, Train Loss: 1.6368, Val PositionMAE: 4.5093
Epoch: 5/200, Train Loss: 1.6207, Val PositionMAE: 4.5431
Epoch: 6/200, Train Loss: 1.5625, Val PositionMAE: 4.6529
Epoch: 7/200, Train Loss: 1.5634, Val PositionMAE: 4.4056
Epoch: 8/200, Train Loss: 1.5678, Val PositionMAE: 4.4189
Epoch: 9/200, Train Loss: 1.6153, Val PositionMAE: 4.5185
Epoch: 10/200, Train Loss: 1.6122, Val PositionMAE: 4.4052
Epoch: 11/200, Train Loss: 1.6150, Val PositionMAE: 4.3188
Epoch: 12/200, Train Loss: 1.5828, Val PositionMAE: 4.3339
Epoch: 13/200, Train Loss: 1.5949, Val PositionMAE: 4.5576
Epoch: 14/200, Train Loss: 1.6231, Val PositionMAE: 4.5121
Epoch: 15/200, Train Loss: 1.5884, Val PositionMAE: 4.6014
Epoch: 16/200, Train Loss: 1.5692, Val PositionMAE: 4.3369
Epoch: 17/200, Train Loss: 1.6100, Val PositionMAE: 4.3742
Epoch: 18/200, Train Loss: 1.6210, Val PositionMAE: 4.2786
Epoch: 19/200, Train Loss: 1.6349, Val PositionMAE: 4.6528
Epoch: 20/200, Train Loss: 1.6258, Val PositionMAE: 4.2255
Epoch: 21/200, Train Loss: 1.5601, Val PositionMAE: 4.7047
Epoch: 22/200, Train Loss: 1.5959, Val PositionMAE: 4.3680
Epoch: 23/200, Train Loss: 1.5853, Val PositionMAE: 4.3822
Epoch: 24/200, Train Loss: 1.5585, Val PositionMAE: 4.2771
Epoch: 25/200, Train Loss: 1.5928, Val PositionMAE: 4.6419
Epoch: 26/200, Train Loss: 1.5875, Val PositionMAE: 4.2994
Epoch: 27/200, Train Loss: 1.6091, Val PositionMAE: 4.6019
Epoch: 28/200, Train Loss: 1.5870, Val PositionMAE: 4.4498
Epoch: 29/200, Train Loss: 1.6095, Val PositionMAE: 4.4619
Epoch: 30/200, Train Loss: 1.6039, Val PositionMAE: 4.2732
Epoch: 31/200, Train Loss: 1.5712, Val PositionMAE: 4.6576
Epoch: 32/200, Train Loss: 1.6110, Val PositionMAE: 4.7926
Epoch: 33/200, Train Loss: 1.6164, Val PositionMAE: 4.5165
Epoch: 34/200, Train Loss: 1.5403, Val PositionMAE: 4.7264
Epoch: 35/200, Train Loss: 1.6010, Val PositionMAE: 4.3685
Epoch: 36/200, Train Loss: 1.6190, Val PositionMAE: 4.6084
Epoch: 37/200, Train Loss: 1.6180, Val PositionMAE: 4.4397
Epoch: 38/200, Train Loss: 1.6340, Val PositionMAE: 4.4245
Epoch: 39/200, Train Loss: 1.6103, Val PositionMAE: 4.5341
Epoch: 40/200, Train Loss: 1.5828, Val PositionMAE: 4.3226
Epoch: 41/200, Train Loss: 1.5572, Val PositionMAE: 4.4764
Epoch: 42/200, Train Loss: 1.5912, Val PositionMAE: 4.4740
Epoch: 43/200, Train Loss: 1.5627, Val PositionMAE: 4.4921
Epoch: 44/200, Train Loss: 1.6151, Val PositionMAE: 4.3992
Epoch: 45/200, Train Loss: 1.6018, Val PositionMAE: 4.4598
Epoch: 46/200, Train Loss: 1.6215, Val PositionMAE: 4.3656
Epoch: 47/200, Train Loss: 1.5838, Val PositionMAE: 4.4348
Epoch: 48/200, Train Loss: 1.6127, Val PositionMAE: 4.6320
Epoch: 49/200, Train Loss: 1.5877, Val PositionMAE: 4.3791
Epoch: 50/200, Train Loss: 1.5682, Val PositionMAE: 4.6244
Maximum patience reached

Training completed in 12.47 seconds
Best validation PositionMAE: 4.2255
Results saved to ./logs/overfitting_test/VectorDiffusion_1069k_h64_T50/seed43

Running with seed: 44

Model Summary for VectorDiffusion:
Total trainable parameters: 1,068,611 (1069k)
Model architecture:
VectorDiffusion(
  (encoder): Encoder(
    (encoder): Sequential(
      (0): Linear(in_features=6000, out_features=64, bias=True)
      (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Dropout(p=0.1, inplace=False)
      (4): Linear(in_features=64, out_features=64, bias=True)
      (5): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (6): Identity()
      (7): Identity()
    )
  )
  (denoiser): VectorPosNet(
    (time_embedding): Sequential(
      (0): Linear(in_features=1, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
      (4): Linear(in_features=64, out_features=64, bias=True)
    )
    (cond_embedding): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
      (4): Linear(in_features=64, out_features=64, bias=True)
    )
    (input_proj): Linear(in_features=3, out_features=64, bias=True)
    (down1): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (pool1): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down2): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=128, bias=True)
      (3): ReLU()
    )
    (pool2): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down3): Sequential(
      (0): Linear(in_features=128, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=256, bias=True)
      (3): ReLU()
    )
    (pool3): AvgPool1d(kernel_size=(5,), stride=(5,), padding=(0,))
    (bottleneck): Sequential(
      (0): Linear(in_features=320, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
    )
    (up3): Linear(in_features=256, out_features=1280, bias=True)
    (up3_conv): Sequential(
      (0): Linear(in_features=256, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=128, bias=True)
      (3): ReLU()
    )
    (up2): Linear(in_features=128, out_features=256, bias=True)
    (up2_conv): Sequential(
      (0): Linear(in_features=128, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (up1): Linear(in_features=64, out_features=128, bias=True)
    (up1_conv): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (output_proj): Linear(in_features=64, out_features=3, bias=True)
  )
)
Epoch: 1/200, Train Loss: 1.5546, Val PositionMAE: 4.1380
Epoch: 2/200, Train Loss: 1.5714, Val PositionMAE: 4.4186
Epoch: 3/200, Train Loss: 1.6170, Val PositionMAE: 4.4664
Epoch: 4/200, Train Loss: 1.6321, Val PositionMAE: 4.4780
Epoch: 5/200, Train Loss: 1.5742, Val PositionMAE: 4.4457
Epoch: 6/200, Train Loss: 1.5692, Val PositionMAE: 4.6136
Epoch: 7/200, Train Loss: 1.6597, Val PositionMAE: 4.2939
Epoch: 8/200, Train Loss: 1.5667, Val PositionMAE: 4.3296
Epoch: 9/200, Train Loss: 1.6023, Val PositionMAE: 4.4189
Epoch: 10/200, Train Loss: 1.6255, Val PositionMAE: 4.3855
Epoch: 11/200, Train Loss: 1.5895, Val PositionMAE: 4.4896
Epoch: 12/200, Train Loss: 1.6135, Val PositionMAE: 4.2598
Epoch: 13/200, Train Loss: 1.6131, Val PositionMAE: 4.5199
Epoch: 14/200, Train Loss: 1.6234, Val PositionMAE: 4.4139
Epoch: 15/200, Train Loss: 1.6081, Val PositionMAE: 4.3699
Epoch: 16/200, Train Loss: 1.5828, Val PositionMAE: 4.3895
Epoch: 17/200, Train Loss: 1.6249, Val PositionMAE: 4.5261
Epoch: 18/200, Train Loss: 1.5713, Val PositionMAE: 4.5563
Epoch: 19/200, Train Loss: 1.6017, Val PositionMAE: 4.5445
Epoch: 20/200, Train Loss: 1.5625, Val PositionMAE: 4.5990
Epoch: 21/200, Train Loss: 1.6096, Val PositionMAE: 4.6880
Epoch: 22/200, Train Loss: 1.6124, Val PositionMAE: 4.5581
Epoch: 23/200, Train Loss: 1.6276, Val PositionMAE: 4.2907
Epoch: 24/200, Train Loss: 1.6110, Val PositionMAE: 4.5269
Epoch: 25/200, Train Loss: 1.5923, Val PositionMAE: 4.2764
Epoch: 26/200, Train Loss: 1.6071, Val PositionMAE: 4.5578
Epoch: 27/200, Train Loss: 1.5816, Val PositionMAE: 4.6684
Epoch: 28/200, Train Loss: 1.5646, Val PositionMAE: 4.5538
Epoch: 29/200, Train Loss: 1.5905, Val PositionMAE: 4.3940
Epoch: 30/200, Train Loss: 1.5664, Val PositionMAE: 4.6425
Epoch: 31/200, Train Loss: 1.5749, Val PositionMAE: 4.5979
Maximum patience reached

Training completed in 8.50 seconds
Best validation PositionMAE: 4.1380
Results saved to ./logs/overfitting_test/VectorDiffusion_1069k_h64_T50/seed44
Results saved to ./logs/overfitting_test/VectorDiffusion_1069k_h64_T50/seed44\results/overfitting_results.csv

,Model,Dataset,Task,Seed,Train samples,Val samples,Train time,Trainable parameters,Train loss,Metric name,Val metric
0,VectorDiffusion,CHILI-3K (5 samples),AbsPositionRegressionxPDF,42,4,1,17.766783,1068611,1.641441,PositionMAE,4.181557
1,VectorDiffusion,CHILI-3K (5 samples),AbsPositionRegressionxPDF,43,4,1,12.474657,1068611,1.568215,PositionMAE,4.225504
2,VectorDiffusion,CHILI-3K (5 samples),AbsPositionRegressionxPDF,44,4,1,8.497436,1068611,1.574851,PositionMAE,4.138016

In [4]:
run_benchmark_overfitting(config_path='./configs/vector_diff_tiny_config.yaml')

Using device: cuda
Created small dataset with 5 samples
Validating dataset (max atoms: 100)...
Dataset validation successful - all structures have appropriate atom counts.
Dataset: CHILI-3K (Small subset for overfitting test)
Task: AbsPositionRegressionxPDF
Model: VectorDiffusion
Training samples: 4
Validation samples: 1

Running with seed: 42

Model Summary for VectorDiffusion:
Total trainable parameters: 364,323 (364k)
Model architecture:
VectorDiffusion(
  (encoder): Encoder(
    (encoder): Sequential(
      (0): Linear(in_features=6000, out_features=32, bias=True)
      (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Dropout(p=0.1, inplace=False)
      (4): Linear(in_features=32, out_features=32, bias=True)
      (5): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (6): Identity()
      (7): Identity()
    )
  )
  (denoiser): VectorPosNet(
    (time_embedding): Sequential(
      (0): Linear(in_features=1, out_features=32, bias=True)
      (1): ReLU()
      (2): Linear(in_features=32, out_features=32, bias=True)
      (3): ReLU()
      (4): Linear(in_features=32, out_features=32, bias=True)
    )
    (cond_embedding): Sequential(
      (0): Linear(in_features=32, out_features=32, bias=True)
      (1): ReLU()
      (2): Linear(in_features=32, out_features=32, bias=True)
      (3): ReLU()
      (4): Linear(in_features=32, out_features=32, bias=True)
    )
    (input_proj): Linear(in_features=3, out_features=32, bias=True)
    (down1): Sequential(
      (0): Linear(in_features=32, out_features=32, bias=True)
      (1): ReLU()
      (2): Linear(in_features=32, out_features=32, bias=True)
      (3): ReLU()
    )
    (pool1): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down2): Sequential(
      (0): Linear(in_features=32, out_features=32, bias=True)
      (1): ReLU()
      (2): Linear(in_features=32, out_features=64, bias=True)
      (3): ReLU()
    )
    (pool2): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down3): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=128, bias=True)
      (3): ReLU()
    )
    (pool3): AvgPool1d(kernel_size=(5,), stride=(5,), padding=(0,))
    (bottleneck): Sequential(
      (0): Linear(in_features=160, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=128, bias=True)
      (3): ReLU()
    )
    (up3): Linear(in_features=128, out_features=640, bias=True)
    (up3_conv): Sequential(
      (0): Linear(in_features=128, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (up2): Linear(in_features=64, out_features=128, bias=True)
    (up2_conv): Sequential(
      (0): Linear(in_features=64, out_features=32, bias=True)
      (1): ReLU()
      (2): Linear(in_features=32, out_features=32, bias=True)
      (3): ReLU()
    )
    (up1): Linear(in_features=32, out_features=64, bias=True)
    (up1_conv): Sequential(
      (0): Linear(in_features=32, out_features=32, bias=True)
      (1): ReLU()
      (2): Linear(in_features=32, out_features=32, bias=True)
      (3): ReLU()
    )
    (output_proj): Linear(in_features=32, out_features=3, bias=True)
  )
)
Epoch: 1/500, Train Loss: 1.5757, Val PositionMAE: 5.0763
Epoch: 2/500, Train Loss: 1.6060, Val PositionMAE: 4.7220
Epoch: 3/500, Train Loss: 1.5872, Val PositionMAE: 5.1236
Epoch: 4/500, Train Loss: 1.5898, Val PositionMAE: 5.2614
Epoch: 5/500, Train Loss: 1.5689, Val PositionMAE: 5.0590
Epoch: 6/500, Train Loss: 1.5496, Val PositionMAE: 4.7569
Epoch: 7/500, Train Loss: 1.5988, Val PositionMAE: 4.8927
Epoch: 8/500, Train Loss: 1.5740, Val PositionMAE: 4.6629
Epoch: 9/500, Train Loss: 1.6152, Val PositionMAE: 4.8985
Epoch: 10/500, Train Loss: 1.5271, Val PositionMAE: 4.7846
Epoch: 11/500, Train Loss: 1.5906, Val PositionMAE: 5.1812
Epoch: 12/500, Train Loss: 1.5648, Val PositionMAE: 5.1613
Epoch: 13/500, Train Loss: 1.5860, Val PositionMAE: 5.0610
Epoch: 14/500, Train Loss: 1.6074, Val PositionMAE: 4.8502
Epoch: 15/500, Train Loss: 1.5774, Val PositionMAE: 5.1566
Epoch: 16/500, Train Loss: 1.6097, Val PositionMAE: 4.6917
Epoch: 17/500, Train Loss: 1.5817, Val PositionMAE: 4.8398
Epoch: 18/500, Train Loss: 1.5795, Val PositionMAE: 4.8478
Epoch: 19/500, Train Loss: 1.6460, Val PositionMAE: 4.9012
Epoch: 20/500, Train Loss: 1.5629, Val PositionMAE: 5.1770
Epoch: 21/500, Train Loss: 1.6211, Val PositionMAE: 5.1789
Epoch: 22/500, Train Loss: 1.6109, Val PositionMAE: 5.1433
Epoch: 23/500, Train Loss: 1.6013, Val PositionMAE: 4.9233
Epoch: 24/500, Train Loss: 1.6046, Val PositionMAE: 5.0650
Epoch: 25/500, Train Loss: 1.5606, Val PositionMAE: 5.2536
Epoch: 26/500, Train Loss: 1.5974, Val PositionMAE: 4.8976
Epoch: 27/500, Train Loss: 1.5836, Val PositionMAE: 5.2868
Epoch: 28/500, Train Loss: 1.5711, Val PositionMAE: 5.0197
Epoch: 29/500, Train Loss: 1.5813, Val PositionMAE: 4.9684
Epoch: 30/500, Train Loss: 1.6026, Val PositionMAE: 4.9738
Epoch: 31/500, Train Loss: 1.5968, Val PositionMAE: 4.8814
Epoch: 32/500, Train Loss: 1.5892, Val PositionMAE: 5.1401
Epoch: 33/500, Train Loss: 1.6160, Val PositionMAE: 4.7751
Epoch: 34/500, Train Loss: 1.6747, Val PositionMAE: 5.1380
Epoch: 35/500, Train Loss: 1.5905, Val PositionMAE: 5.1166
Epoch: 36/500, Train Loss: 1.5890, Val PositionMAE: 5.2017
Epoch: 37/500, Train Loss: 1.6431, Val PositionMAE: 4.7639
Epoch: 38/500, Train Loss: 1.6388, Val PositionMAE: 5.0943
Maximum patience reached

Training completed in 16.09 seconds
Best validation PositionMAE: 4.6629
Results saved to ./logs/overfitting_test/VectorDiffusion_364k_h32_T100/seed42
Results saved to ./logs/overfitting_test/VectorDiffusion_364k_h32_T100/seed42\results/overfitting_results.csv

,Model,Dataset,Task,Seed,Train samples,Val samples,Train time,Trainable parameters,Train loss,Metric name,Val metric
0,VectorDiffusion,CHILI-3K (5 samples),AbsPositionRegressionxPDF,42,4,1,16.092195,364323,1.638791,PositionMAE,4.66293

In [5]:
run_benchmark_overfitting(config_path='./configs/vector_diff_tiny40_bigT_config.yaml')

Using device: cuda
Created small dataset with 5 samples
Validating dataset (max atoms: 100)...
Dataset validation successful - all structures have appropriate atom counts.
Dataset: CHILI-3K (Small subset for overfitting test)
Task: AbsPositionRegressionxPDF
Model: VectorDiffusion
Training samples: 4
Validation samples: 1

Running with seed: 42

Model Summary for VectorDiffusion:
Total trainable parameters: 508,523 (509k)
Model architecture:
VectorDiffusion(
  (encoder): Encoder(
    (encoder): Sequential(
      (0): Linear(in_features=6000, out_features=40, bias=True)
      (1): BatchNorm1d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Dropout(p=0.1, inplace=False)
      (4): Linear(in_features=40, out_features=40, bias=True)
      (5): BatchNorm1d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (6): Identity()
      (7): Identity()
    )
  )
  (denoiser): VectorPosNet(
    (time_embedding): Sequential(
      (0): Linear(in_features=1, out_features=40, bias=True)
      (1): ReLU()
      (2): Linear(in_features=40, out_features=40, bias=True)
      (3): ReLU()
      (4): Linear(in_features=40, out_features=40, bias=True)
    )
    (cond_embedding): Sequential(
      (0): Linear(in_features=40, out_features=40, bias=True)
      (1): ReLU()
      (2): Linear(in_features=40, out_features=40, bias=True)
      (3): ReLU()
      (4): Linear(in_features=40, out_features=40, bias=True)
    )
    (input_proj): Linear(in_features=3, out_features=40, bias=True)
    (down1): Sequential(
      (0): Linear(in_features=40, out_features=40, bias=True)
      (1): ReLU()
      (2): Linear(in_features=40, out_features=40, bias=True)
      (3): ReLU()
    )
    (pool1): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down2): Sequential(
      (0): Linear(in_features=40, out_features=40, bias=True)
      (1): ReLU()
      (2): Linear(in_features=40, out_features=80, bias=True)
      (3): ReLU()
    )
    (pool2): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down3): Sequential(
      (0): Linear(in_features=80, out_features=80, bias=True)
      (1): ReLU()
      (2): Linear(in_features=80, out_features=160, bias=True)
      (3): ReLU()
    )
    (pool3): AvgPool1d(kernel_size=(5,), stride=(5,), padding=(0,))
    (bottleneck): Sequential(
      (0): Linear(in_features=200, out_features=160, bias=True)
      (1): ReLU()
      (2): Linear(in_features=160, out_features=160, bias=True)
      (3): ReLU()
    )
    (up3): Linear(in_features=160, out_features=800, bias=True)
    (up3_conv): Sequential(
      (0): Linear(in_features=160, out_features=80, bias=True)
      (1): ReLU()
      (2): Linear(in_features=80, out_features=80, bias=True)
      (3): ReLU()
    )
    (up2): Linear(in_features=80, out_features=160, bias=True)
    (up2_conv): Sequential(
      (0): Linear(in_features=80, out_features=40, bias=True)
      (1): ReLU()
      (2): Linear(in_features=40, out_features=40, bias=True)
      (3): ReLU()
    )
    (up1): Linear(in_features=40, out_features=80, bias=True)
    (up1_conv): Sequential(
      (0): Linear(in_features=40, out_features=40, bias=True)
      (1): ReLU()
      (2): Linear(in_features=40, out_features=40, bias=True)
      (3): ReLU()
    )
    (output_proj): Linear(in_features=40, out_features=3, bias=True)
  )
)
Epoch: 1/500, Train Loss: 1.5937, Val PositionMAE: 374.8593
Epoch: 2/500, Train Loss: 1.6078, Val PositionMAE: 364.8639
Epoch: 3/500, Train Loss: 1.5837, Val PositionMAE: 333.5138
Epoch: 4/500, Train Loss: 1.6142, Val PositionMAE: 366.3340
Epoch: 5/500, Train Loss: 1.5934, Val PositionMAE: 375.9198
Epoch: 6/500, Train Loss: 1.5902, Val PositionMAE: 349.9510
Epoch: 7/500, Train Loss: 1.6260, Val PositionMAE: 340.9273
Epoch: 8/500, Train Loss: 1.5823, Val PositionMAE: 367.1163
Epoch: 9/500, Train Loss: 1.6260, Val PositionMAE: 361.6128
Epoch: 10/500, Train Loss: 1.5632, Val PositionMAE: 346.4070
Epoch: 11/500, Train Loss: 1.6208, Val PositionMAE: 362.3759
Epoch: 12/500, Train Loss: 1.6340, Val PositionMAE: 351.2318
Epoch: 13/500, Train Loss: 1.5904, Val PositionMAE: 410.1616
Epoch: 14/500, Train Loss: 1.6229, Val PositionMAE: 344.7796
Epoch: 15/500, Train Loss: 1.5863, Val PositionMAE: 367.5312
Epoch: 16/500, Train Loss: 1.6085, Val PositionMAE: 339.1893
Epoch: 17/500, Train Loss: 1.5921, Val PositionMAE: 360.8761
Epoch: 18/500, Train Loss: 1.5892, Val PositionMAE: 370.5856
Epoch: 19/500, Train Loss: 1.5905, Val PositionMAE: 356.1797
Epoch: 20/500, Train Loss: 1.6148, Val PositionMAE: 348.2112
Epoch: 21/500, Train Loss: 1.6037, Val PositionMAE: 345.6492
Epoch: 22/500, Train Loss: 1.6169, Val PositionMAE: 353.3790
Epoch: 23/500, Train Loss: 1.5796, Val PositionMAE: 402.9769
Epoch: 24/500, Train Loss: 1.6094, Val PositionMAE: 355.7909
Epoch: 25/500, Train Loss: 1.6047, Val PositionMAE: 367.8690
Epoch: 26/500, Train Loss: 1.6041, Val PositionMAE: 389.1870
Epoch: 27/500, Train Loss: 1.6097, Val PositionMAE: 360.8114
Epoch: 28/500, Train Loss: 1.5436, Val PositionMAE: 363.9305
Epoch: 29/500, Train Loss: 1.6050, Val PositionMAE: 353.1215
Epoch: 30/500, Train Loss: 1.5782, Val PositionMAE: 364.1744
Epoch: 31/500, Train Loss: 1.5572, Val PositionMAE: 353.1620
Epoch: 32/500, Train Loss: 1.6083, Val PositionMAE: 362.1331
Epoch: 33/500, Train Loss: 1.5811, Val PositionMAE: 374.7721
Maximum patience reached

Training completed in 105.43 seconds
Best validation PositionMAE: 333.5138
Results saved to ./logs/overfitting_test/VectorDiffusion_509k_h40_T1000/seed42
Results saved to ./logs/overfitting_test/VectorDiffusion_509k_h40_T1000/seed42\results/overfitting_results.csv

,Model,Dataset,Task,Seed,Train samples,Val samples,Train time,Trainable parameters,Train loss,Metric name,Val metric
0,VectorDiffusion,CHILI-3K (5 samples),AbsPositionRegressionxPDF,42,4,1,105.427639,508523,1.581098,PositionMAE,333.513824

In [6]:
run_benchmark_overfitting(config_path='./configs/vector_diff_tiny40_smallT_config.yaml')

Using device: cuda
Created small dataset with 5 samples
Validating dataset (max atoms: 100)...
Dataset validation successful - all structures have appropriate atom counts.
Dataset: CHILI-3K (Small subset for overfitting test)
Task: AbsPositionRegressionxPDF
Model: VectorDiffusion
Training samples: 4
Validation samples: 1

Running with seed: 42

Model Summary for VectorDiffusion:
Total trainable parameters: 1,068,611 (1069k)
Model architecture:
VectorDiffusion(
  (encoder): Encoder(
    (encoder): Sequential(
      (0): Linear(in_features=6000, out_features=64, bias=True)
      (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Dropout(p=0.1, inplace=False)
      (4): Linear(in_features=64, out_features=64, bias=True)
      (5): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (6): Identity()
      (7): Identity()
    )
  )
  (denoiser): VectorPosNet(
    (time_embedding): Sequential(
      (0): Linear(in_features=1, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
      (4): Linear(in_features=64, out_features=64, bias=True)
    )
    (cond_embedding): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
      (4): Linear(in_features=64, out_features=64, bias=True)
    )
    (input_proj): Linear(in_features=3, out_features=64, bias=True)
    (down1): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (pool1): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down2): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=128, bias=True)
      (3): ReLU()
    )
    (pool2): AvgPool1d(kernel_size=(2,), stride=(2,), padding=(0,))
    (down3): Sequential(
      (0): Linear(in_features=128, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=256, bias=True)
      (3): ReLU()
    )
    (pool3): AvgPool1d(kernel_size=(5,), stride=(5,), padding=(0,))
    (bottleneck): Sequential(
      (0): Linear(in_features=320, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
    )
    (up3): Linear(in_features=256, out_features=1280, bias=True)
    (up3_conv): Sequential(
      (0): Linear(in_features=256, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=128, bias=True)
      (3): ReLU()
    )
    (up2): Linear(in_features=128, out_features=256, bias=True)
    (up2_conv): Sequential(
      (0): Linear(in_features=128, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (up1): Linear(in_features=64, out_features=128, bias=True)
    (up1_conv): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): ReLU()
    )
    (output_proj): Linear(in_features=64, out_features=3, bias=True)
  )
)
Epoch: 1/500, Train Loss: 1.5939, Val PositionMAE: 4.2115
Epoch: 2/500, Train Loss: 1.5926, Val PositionMAE: 4.2512
Epoch: 3/500, Train Loss: 1.5560, Val PositionMAE: 4.2166
Epoch: 4/500, Train Loss: 1.6201, Val PositionMAE: 4.1409
Epoch: 5/500, Train Loss: 1.6103, Val PositionMAE: 4.1819
Epoch: 6/500, Train Loss: 1.6252, Val PositionMAE: 4.1357
Epoch: 7/500, Train Loss: 1.6252, Val PositionMAE: 4.0378
Epoch: 8/500, Train Loss: 1.6248, Val PositionMAE: 4.0288
Epoch: 9/500, Train Loss: 1.6040, Val PositionMAE: 4.1086
Epoch: 10/500, Train Loss: 1.6336, Val PositionMAE: 4.4320
Epoch: 11/500, Train Loss: 1.5877, Val PositionMAE: 4.1533
Epoch: 12/500, Train Loss: 1.5755, Val PositionMAE: 4.0834
Epoch: 13/500, Train Loss: 1.5956, Val PositionMAE: 4.0766
Epoch: 14/500, Train Loss: 1.6096, Val PositionMAE: 4.1278
Epoch: 15/500, Train Loss: 1.5757, Val PositionMAE: 3.9290
Epoch: 16/500, Train Loss: 1.5977, Val PositionMAE: 4.1385
Epoch: 17/500, Train Loss: 1.5945, Val PositionMAE: 4.3474
Epoch: 18/500, Train Loss: 1.6186, Val PositionMAE: 4.0832
Epoch: 19/500, Train Loss: 1.5880, Val PositionMAE: 4.1486
Epoch: 20/500, Train Loss: 1.5691, Val PositionMAE: 4.0853
Epoch: 21/500, Train Loss: 1.6051, Val PositionMAE: 4.3499
Epoch: 22/500, Train Loss: 1.5708, Val PositionMAE: 4.0659
Epoch: 23/500, Train Loss: 1.5779, Val PositionMAE: 4.4607
Epoch: 24/500, Train Loss: 1.6086, Val PositionMAE: 4.0000
Epoch: 25/500, Train Loss: 1.6139, Val PositionMAE: 4.1151
Epoch: 26/500, Train Loss: 1.6024, Val PositionMAE: 4.1706
Epoch: 27/500, Train Loss: 1.5934, Val PositionMAE: 4.2996
Epoch: 28/500, Train Loss: 1.6255, Val PositionMAE: 4.0805
Epoch: 29/500, Train Loss: 1.5305, Val PositionMAE: 3.9920
Epoch: 30/500, Train Loss: 1.6056, Val PositionMAE: 4.1467
Epoch: 31/500, Train Loss: 1.6277, Val PositionMAE: 4.1240
Epoch: 32/500, Train Loss: 1.6050, Val PositionMAE: 4.0239
Epoch: 33/500, Train Loss: 1.6229, Val PositionMAE: 4.2047
Epoch: 34/500, Train Loss: 1.5845, Val PositionMAE: 4.1884
Epoch: 35/500, Train Loss: 1.5510, Val PositionMAE: 4.0201
Epoch: 36/500, Train Loss: 1.6011, Val PositionMAE: 4.1145
Epoch: 37/500, Train Loss: 1.5653, Val PositionMAE: 4.1386
Epoch: 38/500, Train Loss: 1.5812, Val PositionMAE: 4.1631
Epoch: 39/500, Train Loss: 1.5950, Val PositionMAE: 4.2863
Epoch: 40/500, Train Loss: 1.6043, Val PositionMAE: 4.1587
Epoch: 41/500, Train Loss: 1.6180, Val PositionMAE: 4.2320
Epoch: 42/500, Train Loss: 1.6263, Val PositionMAE: 4.1486
Epoch: 43/500, Train Loss: 1.6254, Val PositionMAE: 4.0650
Epoch: 44/500, Train Loss: 1.6009, Val PositionMAE: 4.1484
Epoch: 45/500, Train Loss: 1.5805, Val PositionMAE: 4.1392
Maximum patience reached

Training completed in 6.74 seconds
Best validation PositionMAE: 3.9290
Results saved to ./logs/overfitting_test/VectorDiffusion_1069k_h64_T10/seed42
Results saved to ./logs/overfitting_test/VectorDiffusion_1069k_h64_T10/seed42\results/overfitting_results.csv

,Model,Dataset,Task,Seed,Train samples,Val samples,Train time,Trainable parameters,Train loss,Metric name,Val metric
0,VectorDiffusion,CHILI-3K (5 samples),AbsPositionRegressionxPDF,42,4,1,6.74287,1068611,1.580505,PositionMAE,3.928998

In [ ]:
run_benchmark_overfitting(config_path='./configs/vector_diff_config_bigT.yaml')